Ofir/aws support all regions
blinkops/blink-aws pull request #3
Opened 2021-06-24 12:37 UTC by itsofirblink

2021-06-25 09:55 UTC, danielsblinkops requested changes

2021-06-25 09:55 UTC, danielsblinkops commented on implementation/implementation.go
> +	if actionParameters["awsRegion"] == "*" {
const it already lol

2021-06-25 09:55 UTC, danielsblinkops commented on implementation/implementation.go
> +			actionParameters["awsRegion"] = region
I think its time to write a wrapper with getters andsetters

2021-06-25 09:55 UTC, danielsblinkops commented on implementation/implementation.go
> +	if actionParameters["awsRegion"] == "*" {
Move this to a func

2021-06-25 09:55 UTC, danielsblinkops commented on implementation/implementation.go
> +				}
dont else here

continue inside the if

2021-06-25 09:55 UTC, danielsblinkops commented on implementation/implementation.go
> +		}
new fuckingline

2021-06-25 09:55 UTC, danielsblinkops commented on aws/awsutil/blinkutil.go
> +	return operationRegions
return an empty slice and not a nil one, even beter a clear error

2021-06-27 18:06 UTC, itsofirblink commented on aws/awsutil/blinkutil.go
> +	return operationRegions
empty slice it is

2021-06-27 18:55 UTC, merged